name: CI

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: deploy on production environment
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/${{ secrets.DEPLOY_PATH_PROD }}
            git pull origin main
            docker compose build
            docker compose up -d
